a = int(input())
b = int(input())
print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)
print(a + b)
print((a + b) / 2)
print(a - b)
print(a * b)
if b != 0:
    print(a / b)
else:
    print("Not possible")